# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT32SystemQueryasimage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t32SystemQueryasimage(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Advanced Reports Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Advanced Reports Test").click()
    self.driver.find_element(By.LINK_TEXT, "Advanced Reports").click()
    self.driver.find_element(By.LINK_TEXT, "System Query").click()
    self.driver.execute_script("$.get( window.location.href.replace(\'page=view\',\'page=system_view\') + \'&as_image=1\', function(data,status,xhr){if(data.indexOf(\'PNG\')>-1&&xhr.getResponseHeader(\'Content-Type\')==\'image/png\'){document.body.setAttribute(\'data-img-ok\',\'1\')};document.body.setAttribute(\'data-img\',\'1\')} )")
    WebDriverWait(self.driver, 60).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body[data-img]")))
    self.vars["imgDownloadOK"] = self.driver.execute_script("return $(\'body[data-img-ok]\').length")
    assert(self.vars["imgDownloadOK"] == 1)
  
