# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT26PDFreportfilefield():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t26PDFreportfilefield(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Advanced Reports Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Advanced Reports Test").click()
    self.driver.find_element(By.LINK_TEXT, "Advanced Reports").click()
    self.driver.find_element(By.LINK_TEXT, "Edit reports").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=pdf_edit\"][href*=\"report_id=pdf\"]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"report_saveable\"][value=\"Y\"]")
    if element.is_selected() != True: element.click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"][value=\"Save Report\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Demographics").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"openAddQuesForm(\'patient_document\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"div_add_field\"]")))
    self.driver.execute_script("$(\'#field_annotation\').val(\"@ADVANCED-REPORT-SAVE(\'pdf\')\")")
    self.driver.find_element(By.XPATH, "//*[@aria-describedby=\"div_add_field\"]//button[contains(.,\'Save\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"div_add_field\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"&id=1\"][href*=\"&page=demographics\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.execute_script("dataEntrySubmit(\'submit-btn-savecontinue\')")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"deleteDocumentConfirm\"][onclick*=\"patient_document\"]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Advanced Reports").click()
    self.driver.find_element(By.LINK_TEXT, "Edit reports").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=pdf_edit\"][href*=\"report_id=pdf\"]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"report_saveable\"][value=\"N\"]")
    if element.is_selected() != True: element.click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"][value=\"Save Report\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"record_status_dashboard.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"&id=1\"][href*=\"&page=demographics\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"deleteDocumentConfirm\"][onclick*=\"patient_document\"]").click()
    self.driver.find_element(By.XPATH, "//*[@aria-describedby=\"remove-file\"]//button[contains(.,\'Yes\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"remove-file\"]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"file_delete_dialog\"]")))
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.execute_script("dataEntrySubmit(\'submit-btn-savecontinue\')")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.execute_script("dataEntrySubmit(\'submit-btn-savecontinue\')")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[onclick*=\"deleteDocumentConfirm\"][onclick*=\"patient_document\"]")
    assert len(elements) == 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.find_element(By.LINK_TEXT, "Demographics").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"openAddQuesForm(\'patient_document\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"div_add_field\"]")))
    self.driver.execute_script("$(\'#field_annotation\').val(\'\')")
    self.driver.find_element(By.XPATH, "//*[@aria-describedby=\"div_add_field\"]//button[contains(.,\'Save\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, "[aria-describedby=\"div_add_field\"]")))
  
